### ISSUE TITLE
New Provider

### ISSUE THREAD

**Issue by adilurrhmn** [Flixclusive/flx-providers#21] opened 2024-07-09 19:41 UTC
### Provider name

Hindi dubbed movies and series 

### Provider URL

Vegamovies, luxmovies 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.

**Comment by rhenwinch** [comment] 2024-07-10 02:41
hello,

it's already been raised here on a duplicate issue.

duplicate of #20

**Closed by rhenwinch** 2024-07-10 02:41 UTC
Labels: provider request

**Comment by rhenwinch** [comment] 2024-07-10 05:38
duplicate of #20

**Comment by rhenwinch** [comment] 2024-07-10 05:38
Duplicate of #20
